import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebars are auto-generated from the docs/ directory structure.
 * The actual sidebar items come from the generated book MDX files.
 */
const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
